apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-monitor
  namespace: dev   # ← ЭНД ЗААВАЛ НЭМ
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-monitor
  template:
    metadata:
      labels:
        app: nextjs-monitor
    spec:
      containers:
      - name: nextjs-monitor
        image: nextjs-monitor:1.1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        # Энд health check нэмбэл илүү сайн (заавал биш)
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
